### ISSUE TITLE
More complicated examples

### ISSUE THREAD

**Issue by derek-adair** [hashicorp/atlas-examples#10]
I'm having trouble picturing how to use Atlas in a more meaningful way.  I know its possible to achieve my goals here, i'm just a bit overwhelmed with all of this as a fairly recent convert to full-stack development.

Anyways, is there any work towards more rich examples?  Like what would it look like if i wanted to implement a thin clientside app w/ nginx proxy, API (any language, but hey python / Django Rest would be neat :p), and perhaps an additional abstraction with a postgres DB?

What if i wanted to use docker containers?

Really i'm just looking for general architectural advice on how to build scalable infrastructure and deploy my code on it.  Do you know of any open source projects that utilize Atlas in any novel ways?

**Comment by sethvargo** [comment]
Hey @derek-adair. Thank you for opening an issue. We are working to add more examples to this repository over the next few months. While we do not have your specific use case outlined, there will definitely be more concrete examples to follow. Watch or start this repository and you'll receive notifications when we publish new guides.

Your point is very valid and we will hopefully have something ready shortly :smile:.

**Comment by derek-adair** [comment]
Very cool.  I'll be evaluating Atlas for the next week or more.  I'm specifically interested in playing around with containers as I find them to be novel.  Im just not exactly sure how all that works just yet, I think I need to do a bit more diving into packer/terraform.   We'll see hopefully I will continue to be impressed and I can add to that list of Open Source examples :)
