### ISSUE TITLE
Clarification about future of Atlas

### ISSUE THREAD

**Issue by rokka-n** [hashicorp/atlas-examples#126]
I'm thinking about the possibility to build AMIs using atlas service, but I have doubts about services availability in Atlas as well as future of Atlas itself. It had consul, applications and vault - all deprecated.

Are there any guarantees about Atlas support and development for the mid- and long-term future?

**Comment by clstokes** [comment]
Hi @rokka-n, the HashiCorp product suite has gone through some changes over the past several months, but all products are still under active development with strong mid and long-term future plans!

To provide more detail the Packer, Terraform, Consul, and Vault features of Atlas have been separated into individual products - Terraform Enterprise (includes Packer and Terraform), Consul Enterprise and Vault Enterprise. If you visit https://www.hashicorp.com/, you can see each product in the Products menu in the header and footer of each page.

If you'd like to talk in more detail about the changes and the future of Terraform Enterprise, please contact us via the form at https://www.hashicorp.com/products/terraform/. 

Thanks!

**Comment by rokka-n** [comment]
Thank you for clarification. 
I guess Packer in atlas remains free for time being? There is no mark "enterprise" on packer service.

**Comment by clstokes** [comment]
@rokka-n Packer is not free, it's considered a part of Terraform Enterprise. This will hopefully become more clear over time as the branding and product changes finalize.
