### ISSUE TITLE
How do i SSH to a server generated via terraform/packer?

### ISSUE THREAD

**Issue by derek-adair** [hashicorp/atlas-examples#14]
I'm trying to set up my consul cluster and I can't seem to figure out how to connect to it!

**Comment by sethvargo** [comment]
Hi @derek-adair,

This repository is for reporting issues with the Atlas examples or documentation. If you have a support issue, please email support@hashicorp.com.

Please email support with more information and we will be happy to help you out. (Sorry to push you to support, but we want to discourage this repository from being an open support forum).

**Comment by derek-adair** [comment]
Is hashicorp active on any public support forums? or is it limited to support@?

**Comment by sethvargo** [comment]
@derek-adair you can use the mailing list, irc, etc, but commercial support for Atlas is provided through HashiCorp support.
