### ISSUE TITLE
Cannot connect Eve API / Mongo DB nodes to consul cluster

### ISSUE THREAD

**Issue by derek-adair** [hashicorp/atlas-examples#18]
Cant seem to get the demo to work... Fairly confident i followed the steps exactly but I am not seeing the nodes on my Atlas infrastructure.  They do show up in my amazon console though... not sure what it could be.

**Comment by sethvargo** [comment]
Hi Derek,

Could you please email support@hashicorp.com for more information. The "issues" in this repository [are for reporting typos](https://github.com/hashicorp/atlas-examples#issues). I'm afraid your issue requires more digging, so please email support and they can help you out.
