### ISSUE TITLE
Consul AWS example deploy problems

### ISSUE THREAD

**Issue by mainframe** [hashicorp/atlas-examples#30]
Followed terraform apply instructions after successful Consul AWS ami artifact build through Atlas - as instructed commented out resource "aws_instance" "consul" and did run terraform apply first on artifact - and then re-enabled aws_instance sections and re-run terraform apply. 3 AWS instances are running in EC2 - but nothing showed up in Atlas infrastructure section. How to debug it further?

**Comment by bitgeeky** [comment]
@mainframe  Can you please confirm if you have right credentials here also https://github.com/hashicorp/atlas-examples/blob/master/consul/ops/upstart/consul_bootstrap.conf#L21

Since this is the only thing not mentioned in README otherwise it works fine for me.

**Comment by mainframe** [comment]
If its not mentioned in the docs - then certainly NOT :) Thanks for mentioning this - I will try again...

**Comment by mainframe** [comment]
Updated upstart configuration and submitted new packer build to Atlas - and getting next error:

```
---- Started new build at 2015-03-19 07:07:28.77474612 +0000 UTC ----
amazon-ebs output will be in this color.

==> amazon-ebs: Inspecting the source AMI...
==> amazon-ebs: Creating temporary keypair: packer 550a75b1-dbd9-86cc-3268-5cf88c0cbb6d
==> amazon-ebs: Creating temporary security group for this instance...
==> amazon-ebs: Authorizing SSH access on the temporary security group...
==> amazon-ebs: Launching a source AWS instance...
==> amazon-ebs: Error finding source instance (i-b19acf41): The instance ID 'i-b19acf41' does not exist (InvalidInstanceID.NotFound)
==> amazon-ebs: Deleting temporary security group...
==> amazon-ebs: Error cleaning up security group. Please delete the group manually: sg-8357c9e7
==> amazon-ebs: Deleting temporary keypair...
Build 'amazon-ebs' errored: Error finding source instance (i-b19acf41): The instance ID 'i-b19acf41' does not exist (InvalidInstanceID.NotFound)

==> Some builds didn't complete successfully and had errors:
--> amazon-ebs: Error finding source instance (i-b19acf41): The instance ID 'i-b19acf41' does not exist (InvalidInstanceID.NotFound)

==> Builds finished but no artifacts were created.
```

**Comment by mainframe** [comment]
Ok - succeeded with the build on next submit - but still infrastructure does not appear after terraform brings consul cluster up in AWS. From AWS VM log I can see only that consul service was started.

How this upstart consul_bootstrap.conf should be populated/updated into AWS consul.ami artefact?
How to debug if it does not work?
Should the parameter be:  -atlas=<username>/infrastructure OR -atlas=<username>/<infrastructure token name> ? ie is this /infrastrusture part static?

**Comment by bitgeeky** [comment]
No this `/infrastructure` part isn't static, its the name of your infrastructure.
For this example lets call it `infrastructure`
If you put in right `<username>/infrastructure` here 
https://github.com/hashicorp/atlas-examples/blob/master/consul/ops/upstart/consul_bootstrap.conf#L21

and correct ATLAS token here  https://github.com/hashicorp/atlas-examples/blob/master/consul/ops/upstart/consul_bootstrap.conf#L23 and build the infrastructure again, it should work perfectly fine.

For debugging you can access the logs at `/var/log/consul.log` in any of the consul nodes and also check the members by running `consul members` on any of the nodes in consul infrastructure.

Hope this helps, for other commands see https://www.consul.io/docs/commands/index.html

**Comment by mainframe** [comment]
I have corrent atlas params in upstart config - yet it still does not work. How one would access these consul AWS VMs for debugging - as currently they dont have any public IP and ssh key assingned by default?

**Comment by bitgeeky** [comment]
Agreed ! We are planning to do an example for pre baking ssh keys in vm's very soon, but for now you can have hints from here:
1 Generate a public/private key pair by creating any dummy instance in AWS.
Add a `debug.sh` file like here https://github.com/hashicorp/atlas-examples/blob/master/LAMP/ops/scripts/debug.sh

and execute it in provisioners like https://github.com/hashicorp/atlas-examples/blob/master/LAMP/ops/apache-php.json#L51

You will also have to make some changes to your terraform configuration to include a security group allowing ssh you can do something like:
https://github.com/hashicorp/atlas-examples/blob/master/LAMP/ops/terraform/lamp.tf#L17

**Comment by mainframe** [comment]
What I did for debug for now - was:
* launched manually test instance from artifact - and assigned ssh keys and public IP as normal
* it is worth to mention somewhere in the docs that cloud-init username that should be used for ssh logins is: ubuntu
* scada registering worked with this manual test there - without any manual changes to the files/configs inside VM - so it hints that problem is related to VPC networking issues/terraform configs perhaps?
