### ISSUE TITLE
Should linked app trigger build of deployable artefact with latest application code?

### ISSUE THREAD

**Issue by boztek** [hashicorp/atlas-examples#5]
Going through the example/ tutorial I'm noticing that updating app code, committing and deploying to atlas with vagrant push is triggering a build of a new AMI for the linked build configuration as expected.

What is not working as expected is the latest application version doesn't appear in the final artefact so after committing a change, vagrant pushing, waiting for triggered build to complete and then terraform applying (which is deploying an AMI with the new id to the web heads) the application is not updated.

Doing a packer push and terraform applying works.

If this is not as expected or doesn't make sense let me know and I'll submit a proper bug report.

**Comment by sethvargo** [comment]
Hi @boztek,

Thank you for opening a report. Just to clarify, you have an application (let's call it "webapp") and when you `vagrant push` webapp, a new build configuration triggers and an artifact is created, but it is not using the correct version of the webapp application?

If possible, could you share some screenshots or more information so we can help you debug? If you would rather talk over private channels, you can email support@hashicorp.com :smile: 

/cc @pearkes

**Comment by sethvargo** [comment]
Hey @boztek I just wanted to check in and see if you made any progress on this? Please let me know if you have any questions.

**Comment by sethvargo** [comment]
We are able to reproduce this internally and will have it fixed as soon as possible.
