### ISSUE TITLE
AWS-SSH-Setup for Atlas?

### ISSUE THREAD

**Issue by steve-jansen** [hashicorp/atlas-examples#52]
Hi!

Does the [AWS-SSH-Setup](
https://github.com/hashicorp/atlas-examples/blob/master/AWS-SSH-Setup/ssh.md) example work with Atlas?

The `ssh_keys/tmp-key` seems to imply a file on your local machine, not something visible to Atlas.

I can imagine hacking something together with Terraform variables in Atlas to store the key pair, and create a local file on disk to use for the SSH connection.  Is there a better way?

Many thanks,
Steve

**Comment by KFishner** [comment]
Hey Steve - when you [`terraform push`](http://terraform.io/docs/commands/push.html) to Atlas, it sends up the files in the directory you pushed from. You probably aren't tracking your ssh_key with a version control system, so you can set -vcs=false in terraform push to send up all files, not just those committed to version control. 

OR

You could just put the contents of the ssh_key file as an Atlas variable, as you described. Then just reference that variable like any other!

**Comment by steve-jansen** [comment]
Hey @KFishner 

Very cool.  Didn't think about the `-vcs=false` option.

Would the key file be protected by Vault?  Or is that a good reason to use a TF variable in Atlas?

Cheers,
Steve

**Comment by KFishner** [comment]
@steve-jansen good questions - the key file would not be protected by Vault for right now. We're working on a more complete integration between Vault <> Atlas that will make this possible though!
